import type { GoogleCalendarEntry, PlannerEvent } from '../types';

export const DEMO_CALENDARS: GoogleCalendarEntry[] = [
  {
    id: 'demo-travel',
    summary: 'Travel Plans',
    backgroundColor: '#51b749',
    foregroundColor: '#ffffff',
    primary: true,
  },
  {
    id: 'demo-family',
    summary: 'Family Time',
    backgroundColor: '#fbd75b',
    foregroundColor: '#1d1d1d',
  },
];

export const DEMO_EVENTS: PlannerEvent[] = [
  {
    id: 'demo-vacation-1',
    calendarId: 'demo-family',
    calendarSummary: 'Family Time',
    title: 'Winter Break',
    startDate: '2026-01-03',
    endDate: '2026-01-10',
    colorId: '2',
    location: 'Alps',
    notes: 'Family skiing trip',
    type: 'vacation',
    managedByYearPlan: true,
    readOnly: false,
  },
  {
    id: 'demo-flight-1',
    calendarId: 'demo-travel',
    calendarSummary: 'Travel Plans',
    title: 'Tokyo Flights',
    startDate: '2026-03-18',
    endDate: '2026-03-20',
    colorId: '11',
    location: 'Berlin to Tokyo',
    notes: 'Outbound + return flight block',
    type: 'flight',
    managedByYearPlan: true,
    readOnly: false,
  },
  {
    id: 'demo-hotel-1',
    calendarId: 'demo-travel',
    calendarSummary: 'Travel Plans',
    title: 'Tokyo Hotel',
    startDate: '2026-03-19',
    endDate: '2026-03-27',
    colorId: '6',
    location: 'Shinjuku',
    notes: 'Stay overlaps flights on purpose',
    type: 'hotel',
    managedByYearPlan: true,
    readOnly: false,
  },
  {
    id: 'demo-travel-1',
    calendarId: 'demo-travel',
    calendarSummary: 'Travel Plans',
    title: 'Japan Trip',
    startDate: '2026-03-18',
    endDate: '2026-03-28',
    colorId: '10',
    location: 'Tokyo + Kyoto',
    notes: 'Main travel block',
    type: 'travel',
    managedByYearPlan: true,
    readOnly: false,
  },
  {
    id: 'demo-holiday-1',
    calendarId: 'demo-family',
    calendarSummary: 'Family Time',
    title: 'Easter Holiday',
    startDate: '2026-04-03',
    endDate: '2026-04-06',
    colorId: '5',
    location: '',
    notes: 'Holiday overlap example',
    type: 'holiday',
    managedByYearPlan: true,
    readOnly: false,
  },
  {
    id: 'demo-vacation-2',
    calendarId: 'demo-family',
    calendarSummary: 'Family Time',
    title: 'Summer Vacation',
    startDate: '2026-07-20',
    endDate: '2026-08-05',
    colorId: '2',
    location: 'Italy',
    notes: 'Long summer block spanning two months',
    type: 'vacation',
    managedByYearPlan: true,
    readOnly: false,
  },
];
